# Generated by Django 5.1.3 on 2024-11-10 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_criterion_criterionid_document_docid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="docId",
        ),
    ]
