# Generated by Django 5.1.3 on 2024-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_document_docid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="max_length",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="metrics",
            field=models.ManyToManyField(blank=True, to="home.metrics"),
        ),
    ]
