# Generated by Django 5.1.3 on 2024-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_metrics_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="documentFile",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
