# Generated by Django 5.1.3 on 2024-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_document_documentfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="documentFile",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
