# Generated by Django 5.0.4 on 2024-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_document_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='dataTemplate',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
